name: google-image-download
base: core22
adopt-info: g-i-d
summary: Tool for searching and downloading Google images to the local hard disk!
description: |
  This program lets you download tons of images from Google. Please do not
  download or use any image that violates its copyright terms. Google Images
  is a search engine that merely indexes images and allows you to find them.
  It does NOT produce its own images and, as such, it doesn't own copyright
  on any of them. The original creators of the images own the copyrights.

grade: stable
confinement: strict

apps:
  google-image-download:
    command: bin/googleimagesdownload
    extensions: [ gnome ]
    plugs:
      - home
      - network
      - network-bind

parts:
  g-i-d:
    plugin: python
    #source: https://github.com/hardikvasa/google-images-download.git
    source: https://github.com/Joeclinton1/google-images-download.git
    build-environment:
      - PYTHONPATH: ''
      - PATH: $SNAPCRAFT_PART_INSTALL/bin:/snap/snapcraft/current/libexec/snapcraft:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    override-build: |
      #env
      VER="$(grep "__version__ =" setup.py | sed "s/^.* = '//;s/'.*$//")"
      craftctl set version=$VER
      snapcraftctl build
